export const locationsSeed = [
  { name: 'Andorra', imagePath: 'locations/ph.png' },
  { name: 'United Arab Emirates', imagePath: 'locations/ph.png' },
  { name: 'Afghanistan', imagePath: 'locations/ph.png' },
  { name: 'Antigua and Barbuda', imagePath: 'locations/ph.png' },
  { name: 'Anguilla', imagePath: 'locations/ph.png' },
  { name: 'Albania', imagePath: 'locations/ph.png' },
  { name: 'Armenia', imagePath: 'locations/ph.png' },
  { name: 'Netherlands Antilles', imagePath: 'locations/ph.png' },
  { name: 'Angola', imagePath: 'locations/ph.png' },
  { name: 'Antarctica', imagePath: 'locations/ph.png' },
  { name: 'Argentina', imagePath: 'locations/ph.png' },
  { name: 'American Samoa', imagePath: 'locations/ph.png' },
  { name: 'Austria', imagePath: 'locations/ph.png' },
  { name: 'Australia', imagePath: 'locations/ph.png' },
  { name: 'Aruba', imagePath: 'locations/ph.png' },
  { name: 'Azerbaijan', imagePath: 'locations/ph.png' },
  { name: 'Bosnia and Herzegovina', imagePath: 'locations/ph.png' },
  { name: 'Barbados', imagePath: 'locations/ph.png' },
  { name: 'Bangladesh', imagePath: 'locations/ph.png' },
  { name: 'Belgium', imagePath: 'locations/ph.png' },
  { name: 'Burkina Faso', imagePath: 'locations/ph.png' },
  { name: 'Bulgaria', imagePath: 'locations/ph.png' },
  { name: 'Bahrain', imagePath: 'locations/ph.png' },
  { name: 'Burundi', imagePath: 'locations/ph.png' },
  { name: 'Benin', imagePath: 'locations/ph.png' },
  { name: 'Bermuda', imagePath: 'locations/ph.png' },
  { name: 'Brunei', imagePath: 'locations/ph.png' },
  { name: 'Bolivia', imagePath: 'locations/ph.png' },
  { name: 'Brazil', imagePath: 'locations/ph.png' },
  { name: 'Bahamas', imagePath: 'locations/ph.png' },
  { name: 'Bhutan', imagePath: 'locations/ph.png' },
  { name: 'Bouvet Island', imagePath: 'locations/ph.png' },
  { name: 'Botswana', imagePath: 'locations/ph.png' },
  { name: 'Belarus', imagePath: 'locations/ph.png' },
  { name: 'Belize', imagePath: 'locations/ph.png' },
  { name: 'Canada', imagePath: 'locations/ph.png' },
  { name: 'Cocos [Keeling] Islands', imagePath: 'locations/ph.png' },
  { name: 'Congo [DRC]', imagePath: 'locations/ph.png' },
  { name: 'Central African Republic', imagePath: 'locations/ph.png' },
  { name: 'Congo [Republic]', imagePath: 'locations/ph.png' },
  { name: 'Switzerland', imagePath: 'locations/ph.png' },
  { name: "Côte d'Ivoire", imagePath: 'locations/ph.png' },
  { name: 'Cook Islands', imagePath: 'locations/ph.png' },
  { name: 'Chile', imagePath: 'locations/ph.png' },
  { name: 'Cameroon', imagePath: 'locations/ph.png' },
  { name: 'China', imagePath: 'locations/china.png' },
  { name: 'Colombia', imagePath: 'locations/ph.png' },
  { name: 'Costa Rica', imagePath: 'locations/ph.png' },
  { name: 'Cuba', imagePath: 'locations/ph.png' },
  { name: 'Cape Verde', imagePath: 'locations/ph.png' },
  { name: 'Christmas Island', imagePath: 'locations/ph.png' },
  { name: 'Cyprus', imagePath: 'locations/ph.png' },
  { name: 'Czech Republic', imagePath: 'locations/ph.png' },
  { name: 'Germany', imagePath: 'locations/germany.png' },
  { name: 'Djibouti', imagePath: 'locations/ph.png' },
  { name: 'Denmark', imagePath: 'locations/ph.png' },
  { name: 'Dominica', imagePath: 'locations/ph.png' },
  { name: 'Dominican Republic', imagePath: 'locations/ph.png' },
  { name: 'Algeria', imagePath: 'locations/ph.png' },
  { name: 'Ecuador', imagePath: 'locations/ph.png' },
  { name: 'Estonia', imagePath: 'locations/ph.png' },
  { name: 'Egypt', imagePath: 'locations/ph.png' },
  { name: 'Western Sahara', imagePath: 'locations/ph.png' },
  { name: 'Eritrea', imagePath: 'locations/ph.png' },
  { name: 'Spain', imagePath: 'locations/spain.png' },
  { name: 'Ethiopia', imagePath: 'locations/ph.png' },
  { name: 'Finland', imagePath: 'locations/ph.png' },
  { name: 'Fiji', imagePath: 'locations/ph.png' },
  { name: 'Falkland Islands [Islas Malvinas]', imagePath: 'locations/ph.png' },
  { name: 'Micronesia', imagePath: 'locations/ph.png' },
  { name: 'Faroe Islands', imagePath: 'locations/ph.png' },
  { name: 'France', imagePath: 'locations/france.png' },
  { name: 'Gabon', imagePath: 'locations/ph.png' },
  { name: 'United Kingdom', imagePath: 'locations/gb.png' },
  { name: 'Grenada', imagePath: 'locations/ph.png' },
  { name: 'Georgia', imagePath: 'locations/ph.png' },
  { name: 'French Guiana', imagePath: 'locations/ph.png' },
  { name: 'Guernsey', imagePath: 'locations/ph.png' },
  { name: 'Ghana', imagePath: 'locations/ph.png' },
  { name: 'Gibraltar', imagePath: 'locations/ph.png' },
  { name: 'Greenland', imagePath: 'locations/ph.png' },
  { name: 'Gambia', imagePath: 'locations/ph.png' },
  { name: 'Guinea', imagePath: 'locations/ph.png' },
  { name: 'Guadeloupe', imagePath: 'locations/ph.png' },
  { name: 'Equatorial Guinea', imagePath: 'locations/ph.png' },
  { name: 'Greece', imagePath: 'locations/ph.png' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    imagePath: 'locations/ph.png',
  },
  { name: 'Guatemala', imagePath: 'locations/ph.png' },
  { name: 'Guam', imagePath: 'locations/ph.png' },
  { name: 'Guinea-Bissau', imagePath: 'locations/ph.png' },
  { name: 'Guyana', imagePath: 'locations/ph.png' },
  { name: 'Gaza Strip', imagePath: 'locations/ph.png' },
  { name: 'Hong Kong', imagePath: 'locations/ph.png' },
  { name: 'Heard Island and McDonald Islands', imagePath: 'locations/ph.png' },
  { name: 'Honduras', imagePath: 'locations/ph.png' },
  { name: 'Croatia', imagePath: 'locations/ph.png' },
  { name: 'Haiti', imagePath: 'locations/ph.png' },
  { name: 'Hungary', imagePath: 'locations/ph.png' },
  { name: 'Indonesia', imagePath: 'locations/ph.png' },
  { name: 'Ireland', imagePath: 'locations/ph.png' },
  { name: 'Israel', imagePath: 'locations/ph.png' },
  { name: 'Isle of Man', imagePath: 'locations/ph.png' },
  { name: 'India', imagePath: 'locations/ph.png' },
  { name: 'British Indian Ocean Territory', imagePath: 'locations/ph.png' },
  { name: 'Iraq', imagePath: 'locations/ph.png' },
  { name: 'Iran', imagePath: 'locations/ph.png' },
  { name: 'Iceland', imagePath: 'locations/ph.png' },
  { name: 'Italy', imagePath: 'locations/ph.png' },
  { name: 'Jersey', imagePath: 'locations/ph.png' },
  { name: 'Jamaica', imagePath: 'locations/ph.png' },
  { name: 'Jordan', imagePath: 'locations/ph.png' },
  { name: 'Japan', imagePath: 'locations/japan.png' },
  { name: 'Kenya', imagePath: 'locations/ph.png' },
  { name: 'Kyrgyzstan', imagePath: 'locations/ph.png' },
  { name: 'Cambodia', imagePath: 'locations/ph.png' },
  { name: 'Kiribati', imagePath: 'locations/ph.png' },
  { name: 'Comoros', imagePath: 'locations/ph.png' },
  { name: 'Saint Kitts and Nevis', imagePath: 'locations/ph.png' },
  { name: 'North Korea', imagePath: 'locations/ph.png' },
  { name: 'South Korea', imagePath: 'locations/ph.png' },
  { name: 'Kuwait', imagePath: 'locations/ph.png' },
  { name: 'Cayman Islands', imagePath: 'locations/ph.png' },
  { name: 'Kazakhstan', imagePath: 'locations/ph.png' },
  { name: 'Laos', imagePath: 'locations/ph.png' },
  { name: 'Lebanon', imagePath: 'locations/ph.png' },
  { name: 'Saint Lucia', imagePath: 'locations/ph.png' },
  { name: 'Liechtenstein', imagePath: 'locations/ph.png' },
  { name: 'Sri Lanka', imagePath: 'locations/ph.png' },
  { name: 'Liberia', imagePath: 'locations/ph.png' },
  { name: 'Lesotho', imagePath: 'locations/ph.png' },
  { name: 'Lithuania', imagePath: 'locations/ph.png' },
  { name: 'Luxembourg', imagePath: 'locations/ph.png' },
  { name: 'Latvia', imagePath: 'locations/ph.png' },
  { name: 'Libya', imagePath: 'locations/ph.png' },
  { name: 'Morocco', imagePath: 'locations/ph.png' },
  { name: 'Monaco', imagePath: 'locations/ph.png' },
  { name: 'Moldova', imagePath: 'locations/ph.png' },
  { name: 'Montenegro', imagePath: 'locations/ph.png' },
  { name: 'Madagascar', imagePath: 'locations/ph.png' },
  { name: 'Marshall Islands', imagePath: 'locations/ph.png' },
  { name: 'Macedonia [FYROM]', imagePath: 'locations/ph.png' },
  { name: 'Mali', imagePath: 'locations/ph.png' },
  { name: 'Myanmar [Burma]', imagePath: 'locations/ph.png' },
  { name: 'Mongolia', imagePath: 'locations/ph.png' },
  { name: 'Macau', imagePath: 'locations/ph.png' },
  { name: 'Northern Mariana Islands', imagePath: 'locations/ph.png' },
  { name: 'Martinique', imagePath: 'locations/ph.png' },
  { name: 'Mauritania', imagePath: 'locations/ph.png' },
  { name: 'Montserrat', imagePath: 'locations/ph.png' },
  { name: 'Malta', imagePath: 'locations/ph.png' },
  { name: 'Mauritius', imagePath: 'locations/ph.png' },
  { name: 'Maldives', imagePath: 'locations/ph.png' },
  { name: 'Malawi', imagePath: 'locations/ph.png' },
  { name: 'Mexico', imagePath: 'locations/ph.png' },
  { name: 'Malaysia', imagePath: 'locations/ph.png' },
  { name: 'Mozambique', imagePath: 'locations/ph.png' },
  { name: 'Namibia', imagePath: 'locations/ph.png' },
  { name: 'New Caledonia', imagePath: 'locations/ph.png' },
  { name: 'Niger', imagePath: 'locations/ph.png' },
  { name: 'Norfolk Island', imagePath: 'locations/ph.png' },
  { name: 'Nigeria', imagePath: 'locations/ph.png' },
  { name: 'Nicaragua', imagePath: 'locations/ph.png' },
  { name: 'Netherlands', imagePath: 'locations/ph.png' },
  { name: 'Norway', imagePath: 'locations/ph.png' },
  { name: 'Nepal', imagePath: 'locations/ph.png' },
  { name: 'Nauru', imagePath: 'locations/ph.png' },
  { name: 'Niue', imagePath: 'locations/ph.png' },
  { name: 'New Zealand', imagePath: 'locations/ph.png' },
  { name: 'Oman', imagePath: 'locations/ph.png' },
  { name: 'Panama', imagePath: 'locations/ph.png' },
  { name: 'Peru', imagePath: 'locations/ph.png' },
  { name: 'French Polynesia', imagePath: 'locations/ph.png' },
  { name: 'Papua New Guinea', imagePath: 'locations/ph.png' },
  { name: 'Philippines', imagePath: 'locations/ph.png' },
  { name: 'Pakistan', imagePath: 'locations/ph.png' },
  { name: 'Poland', imagePath: 'locations/ph.png' },
  { name: 'Saint Pierre and Miquelon', imagePath: 'locations/ph.png' },
  { name: 'Pitcairn Islands', imagePath: 'locations/ph.png' },
  { name: 'Puerto Rico', imagePath: 'locations/ph.png' },
  { name: 'Palestinian Territories', imagePath: 'locations/ph.png' },
  { name: 'Portugal', imagePath: 'locations/ph.png' },
  { name: 'Palau', imagePath: 'locations/ph.png' },
  { name: 'Paraguay', imagePath: 'locations/ph.png' },
  { name: 'Qatar', imagePath: 'locations/ph.png' },
  { name: 'Réunion', imagePath: 'locations/ph.png' },
  { name: 'Romania', imagePath: 'locations/ph.png' },
  { name: 'Serbia', imagePath: 'locations/ph.png' },
  { name: 'Russian Federation', imagePath: 'locations/russia.png' },
  { name: 'Rwanda', imagePath: 'locations/ph.png' },
  { name: 'Saudi Arabia', imagePath: 'locations/ph.png' },
  { name: 'Solomon Islands', imagePath: 'locations/ph.png' },
  { name: 'Seychelles', imagePath: 'locations/ph.png' },
  { name: 'Sudan', imagePath: 'locations/ph.png' },
  { name: 'Sweden', imagePath: 'locations/ph.png' },
  { name: 'Singapore', imagePath: 'locations/ph.png' },
  { name: 'Saint Helena', imagePath: 'locations/ph.png' },
  { name: 'Slovenia', imagePath: 'locations/ph.png' },
  { name: 'Svalbard and Jan Mayen', imagePath: 'locations/ph.png' },
  { name: 'Slovakia', imagePath: 'locations/ph.png' },
  { name: 'Sierra Leone', imagePath: 'locations/ph.png' },
  { name: 'San Marino', imagePath: 'locations/ph.png' },
  { name: 'Senegal', imagePath: 'locations/ph.png' },
  { name: 'Somalia', imagePath: 'locations/ph.png' },
  { name: 'Suriname', imagePath: 'locations/ph.png' },
  { name: 'São Tomé and Príncipe', imagePath: 'locations/ph.png' },
  { name: 'El Salvador', imagePath: 'locations/ph.png' },
  { name: 'Syria', imagePath: 'locations/ph.png' },
  { name: 'Swaziland', imagePath: 'locations/ph.png' },
  { name: 'Turks and Caicos Islands', imagePath: 'locations/ph.png' },
  { name: 'Chad', imagePath: 'locations/ph.png' },
  { name: 'French Southern Territories', imagePath: 'locations/ph.png' },
  { name: 'Togo', imagePath: 'locations/ph.png' },
  { name: 'Thailand', imagePath: 'locations/ph.png' },
  { name: 'Tajikistan', imagePath: 'locations/ph.png' },
  { name: 'Tokelau', imagePath: 'locations/ph.png' },
  { name: 'Timor-Leste', imagePath: 'locations/ph.png' },
  { name: 'Turkmenistan', imagePath: 'locations/ph.png' },
  { name: 'Tunisia', imagePath: 'locations/ph.png' },
  { name: 'Tonga', imagePath: 'locations/ph.png' },
  { name: 'Turkey', imagePath: 'locations/ph.png' },
  { name: 'Trinidad and Tobago', imagePath: 'locations/ph.png' },
  { name: 'Tuvalu', imagePath: 'locations/ph.png' },
  { name: 'Taiwan', imagePath: 'locations/ph.png' },
  { name: 'Tanzania', imagePath: 'locations/ph.png' },
  { name: 'Ukraine', imagePath: 'locations/ph.png' },
  { name: 'Uganda', imagePath: 'locations/ph.png' },
  { name: 'U.S. Minor Outlying Islands', imagePath: 'locations/ph.png' },
  { name: 'United States', imagePath: 'locations/ph.png' },
  { name: 'Uruguay', imagePath: 'locations/ph.png' },
  { name: 'Uzbekistan', imagePath: 'locations/ph.png' },
  { name: 'Vatican City', imagePath: 'locations/ph.png' },
  { name: 'Saint Vincent and the Grenadines', imagePath: 'locations/ph.png' },
  { name: 'Venezuela', imagePath: 'locations/ph.png' },
  { name: 'British Virgin Islands', imagePath: 'locations/ph.png' },
  { name: 'U.S. Virgin Islands', imagePath: 'locations/ph.png' },
  { name: 'Vietnam', imagePath: 'locations/ph.png' },
  { name: 'Vanuatu', imagePath: 'locations/ph.png' },
  { name: 'Wallis and Futuna', imagePath: 'locations/ph.png' },
  { name: 'Samoa', imagePath: 'locations/ph.png' },
  { name: 'Kosovo', imagePath: 'locations/ph.png' },
  { name: 'Yemen', imagePath: 'locations/ph.png' },
  { name: 'Mayotte', imagePath: 'locations/ph.png' },
  { name: 'South Africa', imagePath: 'locations/ph.png' },
  { name: 'Zambia', imagePath: 'locations/ph.png' },
  { name: 'Zimbabwe', imagePath: 'locations/ph.png' },
];
