export const specialitiesSeed = [
  { name: 'Audio & Sound Editing' },
  { name: 'Audio & Sound Recording' },
  { name: 'Business Consulting' },
  { name: 'Content Marketing' },
  { name: 'Copywriting' },
  { name: 'Data science and analysis' },
  { name: 'Databases' },
  { name: 'Essays' },
  { name: 'Fashion' },
  { name: 'Filmmaking' },
  { name: 'Finance & Accounting' },
  { name: 'Game Development' },
  { name: 'Graphic design' },
  { name: 'Image editing' },
  { name: 'Interior/Exterior design' },
  { name: 'Label/Merchandising' },
  { name: 'Legal Services' },
  { name: 'Logo design' },
  { name: 'Management & Development' },
  { name: 'Mindset coaching' },
  { name: 'Mobile App Development' },
  { name: 'Music Production' },
  { name: 'Music Writing' },
  { name: 'Podcast Marketing' },
  { name: 'Professional Photography' },
  { name: 'Programming and coding' },
  { name: 'Resumes, CVs&Cover Letters' },
  { name: 'SEO' },
  { name: 'Social media analysis' },
  { name: 'Social media marketing' },
  { name: 'Social media monitoring' },
  { name: 'Social media strategy' },
  { name: 'Software Testing' },
  { name: 'Tax Consulting & Advising' },
  { name: 'Transcription' },
  { name: 'Translation' },
  { name: 'Video editing' },
  { name: 'Video Marketing' },
  { name: 'Videography' },
  { name: 'Web Analytics' },
  { name: 'Web design' },
  { name: 'Website Development' },
  { name: 'Cryptocurrency' },
  { name: 'Arts and crafts' },
  { name: 'Personal stylists' },
  { name: 'Wellness' },
  { name: 'Other' },
];
